/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=test --include-runtime=false --env-interface=CloudflareEnv` (hash: 45c9fa7401bf62ee198536b20cb21292)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
