/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=test --include-runtime=false --env-interface=CloudflareEnv` (hash: c20e95760fcc8e2658f38d117b34664d)
interface __BaseEnv_CloudflareEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
